# standard jekyll configuration

permalink: /articles/:title
pygments: true
exclude: ['Rakefile', 'config.rb', 'README.md', 'gems']
markdown: rdiscount

# configuration required for some pages

domain: factt.github.io
title: FACTT
author: The FACTT Team
email: info@factt.org

# configuration for enhancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
    username: factt/factt.github.io

# disqus:
#    id: facttorg
